# notebook to reformat cisbp files to meme and other issues
[all based on the files in the 2018 Lambert et al review "The Human Transcription Factors"]

In [1]:
import numpy as np
import os
import pandas as pd
import sys

## variables

In [2]:
tf_info_f = "00__metadata/TF_info.txt"
motif_info_f = "00__metadata/motif_info.txt"

In [3]:
pwm_dir = "01__pwms"

## 1. import data

In [4]:
tf_info = pd.read_table(tf_info_f, sep="\t")
tf_info.head()

,Ensembl ID,HGNC symbol,DBD,Is TF?,TF assessment,Binding mode,Motif status,Final Notes,Final Comments,Interpro ID(s),...,Vaquerizas 2009 classification,CisBP considers it a TF?,TFCat classification,Is a GO TF?,Initial assessment,Curator 1,Curator 2,TFclass considers it a TF?,Go Evidence,Pfam Domains (By ENSP ID)
0,ENSG00000137203,TFAP2A,AP-2,Yes,Known motif,Monomer or homomultimer,High-throughput in vitro,NaN,NaN,IPR008121;IPR013854,...,a,Yes,TF Gene_DNA-Binding: sequence-specific_DNA Bin...,Yes,"1a1, Direct HQ evidence",Sam Lambert,Yimeng Yin,Yes,$#ENSG00000137203#GO:0000981#sequence-specific...,$#ENSP00000368928#ENSG00000137203#ENST00000379...
1,ENSG00000008196,TFAP2B,AP-2,Yes,Known motif,Monomer or homomultimer,High-throughput in vitro,NaN,NaN,IPR008122;IPR013854,...,a,Yes,TF Gene_DNA-Binding: sequence-specific_DNA Bin...,Yes,"1a1, Direct HQ evidence",Matt Weirauch,Yimeng Yin,Yes,$#ENSG00000008196#GO:0000981#sequence-specific...,$#ENSP00000377265#ENSG00000008196#ENST00000393...
2,ENSG00000087510,TFAP2C,AP-2,Yes,Known motif,Monomer or homomultimer,High-throughput in vitro,NaN,NaN,IPR008123;IPR013854,...,a,Yes,No,Yes,"1a1, Direct HQ evidence",Matt Weirauch,Yimeng Yin,Yes,$#ENSG00000087510#GO:0001077#RNA polymerase II...,$#ENSP00000201031#ENSG00000087510#ENST00000201...
3,ENSG00000008197,TFAP2D,AP-2,Yes,Known motif,Monomer or homomultimer,In vivo/Misc source,Only known motifs are from Transfac or HocoMoc...,Binds the same GCCTGAGGC sequence as the other...,IPR013854;,...,a,Yes,No,Yes,"2a1, Lower confidence direct evidence",Arttu Jolma,Sam Lambert,Yes,$#ENSG00000008197#GO:0000981#sequence-specific...,$#ENSP00000008391#ENSG00000008197#ENST00000008...
4,ENSG00000116819,TFAP2E,AP-2,Yes,Known motif,Monomer or homomultimer,High-throughput in vitro,NaN,NaN,IPR013854;,...,a,Yes,TF Gene_DNA-Binding: sequence-specific_DNA Bin...,Yes,"1a1, Direct HQ evidence",Sam Lambert,Laura Campitelli,Yes,$#ENSG00000116819#GO:0000981#sequence-specific...,$#ENSP00000362332#ENSG00000116819#ENST00000373...

In [5]:
motif_info = pd.read_table(motif_info_f, sep="\t")
motif_info = motif_info[~pd.isnull(motif_info['CIS-BP ID'])]
motif_info.head()

,Ensembl ID,HGNC symbol,Motif evidence,Motif ID,Motif type,Motif source,CIS-BP ID,Best Motif(s)? (Figure 2A)
0,ENSG00000267281,AC023509.3,"Inferred - ATF7 (100% AA Identity, Homo sapiens)",ATF7_eDBD_HT-SELEX,HT-SELEX,Yin2017,M08490_1.94d,True
1,ENSG00000267281,AC023509.3,"Inferred - ATF7 (100% AA Identity, Homo sapiens)",ATF7_eDBD_Methyl-HT-SELEX,Methyl-HT-SELEX,Yin2017,M08491_1.94d,NaN
2,ENSG00000267281,AC023509.3,"Inferred - Atf7 (98% AA Identity, Mus musculus)",3T3L1-Atf7_GSE56872,Misc,HOMER,M06975_1.94d,NaN
3,ENSG00000264668,AC138696.1,"Inferred - ZFP41 (100% AA Identity, Homo sapiens)",ZFP41_FL_HT-SELEX,HT-SELEX,Yin2017,M09315_1.94d,True
4,ENSG00000264668,AC138696.1,"Inferred - ZFP41 (100% AA Identity, Homo sapiens)",ZFP41_FL_Methyl-HT-SELEX,Methyl-HT-SELEX,Yin2017,M09316_1.94d,NaN

## 2. read in motif files

In [6]:
motifs = {}

In [54]:
files = os.listdir(pwm_dir)
files = [f for f in files if "README" not in f]
print("n files: %s" % (len(files)))
for f in files:
    
    motif = f.split(".")[0]
    with open("%s/%s" % (pwm_dir, f)) as fp:
        for line in fp:
            if line.startswith("Pos"):
                continue
            info = line.split()
            if info[0] == "1":
                pwm = []

            info = line.split()
            
            # round the pwm info to 5 decimal points
            info = [round(float(x), 5) for x in info]
            
            pwm.append(info[1:])
    motifs[motif] = pwm

n files: 5597

In [55]:
list(motifs.keys())[0:5]

['HKR1', 'M00117_1', 'M00118_1', 'M00119_1', 'M00120_1']

In [56]:
motifs['HKR1']

[[0.26377, 0.36123, 0.22564, 0.14936],
 [0.08157, 0.46716, 0.1197, 0.33157],
 [0.10275, 0.32309, 0.24258, 0.33157],
 [0.22987, 0.19598, 0.40784, 0.16631],
 [0.01377, 0.32733, 0.17055, 0.48835],
 [0.16208, 0.31038, 0.45869, 0.06886],
 [0.03496, 0.16208, 0.1536, 0.64936],
 [0.00106, 0.96292, 0.00106, 0.03496],
 [0.00106, 0.99259, 0.00106, 0.0053],
 [0.00106, 0.00106, 0.00106, 0.99682],
 [0.00106, 0.82733, 0.00953, 0.16208],
 [0.00106, 0.99682, 0.00106, 0.00106],
 [0.19174, 0.57309, 0.00106, 0.23411],
 [0.09004, 0.32733, 0.09428, 0.48835],
 [0.29343, 0.24258, 0.30614, 0.15784],
 [0.06886, 0.20021, 0.53919, 0.19174],
 [0.01801, 0.31886, 0.08157, 0.58157],
 [0.08581, 0.46716, 0.30614, 0.14089],
 [0.13242, 0.62818, 0.11123, 0.12818],
 [0.34004, 0.38242, 0.17055, 0.10699],
 [0.07733, 0.36547, 0.36123, 0.19598]]

## 3. map motifs to curated TFs

In [57]:
curated_tfs = set(tf_info[tf_info["Is TF?"] == "Yes"]["Ensembl ID"])
len(curated_tfs)

1639

In [69]:
curated_motif_map = {}
curated_pwms = {}

for key in motifs:
    gene = motif_info[motif_info["CIS-BP ID"].str.contains(key)]["Ensembl ID"].iloc[0]
    gene_name = motif_info[motif_info["CIS-BP ID"].str.contains(key)]["HGNC symbol"].iloc[0]
    if gene in curated_tfs:
        pwm = motifs[key]
        
        # make sure the pwm sums to 1 in all rows!
        arr = np.asarray(pwm, dtype=np.float64)
        s = arr.sum(axis=1)
        if (s < 0.99).any() or (s > 1.01).any():
            print("bad motif: %s | len: %s | sums: %s" % (key, len(pwm), s))
        else:
            curated_pwms[key] = motifs[key]
            curated_motif_map[key] = {"gene_id": gene, "gene_name": gene_name}

bad motif: M06403_1 | len: 22 | sums: [ 1.       1.       1.00001  1.       0.99999  1.       1.       1.00001
  1.       1.00001  1.       0.       0.99999  0.99999  0.99999  0.99999
  1.       1.       1.       1.       0.99999  1.     ]
bad motif: M07090_1 | len: 32 | sums: [ 1.00001  1.       1.00001  1.       1.       1.       1.00001  1.
  1.00001  1.       0.       0.99999  0.99999  1.       1.       1.       1.
  1.       1.       1.       1.       0.       1.       1.       1.00001
  0.99999  0.99999  0.99999  1.       1.       1.       1.     ]
bad motif: M07127_1 | len: 50 | sums: [ 1.       1.00001  1.       1.       0.99999  1.       0.99999  1.00001
  0.99999  1.       1.00001  1.00001  1.       1.       1.       0.       1.
  1.       1.       1.       1.       1.       1.       1.       1.       1.
  1.       1.       1.00001  1.       1.       1.       1.       1.       0.
  1.       1.00001  1.       1.       1.       1.       1.       0.99999
  1.       1.       1.00001  1.       1.       1.       1.     ]
bad motif: M07141_1 | len: 23 | sums: [ 1.       1.       1.       1.       1.       1.       1.       0.       1.
  1.00001  1.       1.       0.99999  1.       1.       1.       0.99999
  0.99999  0.99999  1.       1.       1.       1.00001]
bad motif: M10257_1 | len: 19 | sums: [ 1.     1.     1.     1.     1.     0.999  1.     1.     0.     1.     1.
  1.001  1.     1.     0.999  1.     1.     1.     1.   ]
bad motif: M10277_1 | len: 41 | sums: [ 1.     0.999  1.     1.001  1.     0.999  0.999  1.     1.001  1.     1.001
  0.999  1.     1.     1.     0.     0.999  1.     1.     1.     0.999  1.
  1.     1.     1.     0.999  1.     0.999  1.     0.     1.     1.     1.
  1.     1.     0.999  1.001  1.     0.999  1.     1.   ]
bad motif: M10278_1 | len: 25 | sums: [ 1.001  0.999  1.001  1.001  0.999  1.     1.     0.999  1.     1.     1.
  1.     1.001  1.     1.001  0.     1.     0.999  1.     1.     1.001  1.
  0.999  1.001  1.001]
bad motif: M10282_1 | len: 28 | sums: [ 1.       1.       1.       0.999    1.       1.       0.999    1.       0.999
  1.       1.       1.       0.       1.00001  1.00001  1.       0.99999
  1.       1.       1.       1.       1.       1.       1.       1.       1.
  1.       1.     ]
bad motif: M10283_1 | len: 45 | sums: [ 1.001  1.001  1.001  1.001  1.001  1.     1.001  0.     1.001  1.001
  0.999  1.001  1.     1.     0.999  1.001  1.     0.999  0.999  1.     1.
  1.     1.     1.     1.     1.     0.     1.001  1.001  0.999  1.001  1.
  1.     0.999  1.001  1.     0.999  0.999  1.     1.     1.     1.     1.
  1.     1.   ]
bad motif: M10303_1 | len: 26 | sums: [ 0.999  1.     1.     1.     1.     1.     1.     1.001  1.     1.     1.001
  1.     0.999  1.     0.999  0.999  1.     0.     1.     1.     0.999  1.
  1.     1.001  1.     1.   ]
bad motif: M10311_1 | len: 13 | sums: [ 0.8    1.     1.001  1.     1.     1.001  1.     1.001  1.     1.     1.001
  1.     1.   ]

In [70]:
curated_motif_map = pd.DataFrame.from_dict(curated_motif_map, orient="index").reset_index()
curated_motif_map.head()

      index          gene_id gene_name
0      HKR1  ENSG00000181666      HKR1
1  M00117_1  ENSG00000137203    TFAP2A
2  M00118_1  ENSG00000137203    TFAP2A
3  M00119_1  ENSG00000137203    TFAP2A
4  M00120_1  ENSG00000137203    TFAP2A

In [71]:
len(curated_motif_map["gene_id"].unique())

927

In [72]:
len(curated_motif_map)

5586

## 4. convert to MEME format (for FIMO)

In [73]:
out_f = "../01__meme_files/human_curated_tfs.txt"

with open(out_f, "w") as f:
    f.write("MEME version 4\n\n")
    f.write("ALPHABET= ACGT\n\n")
    f.write("strands: + -\n\n")
    f.write("Background letter frequencies (from uniform background):\nA 0.25000 C 0.25000 G 0.25000 T 0.25000\n\n")

    # now write the motifs
    for key in curated_pwms:
        #print(key)

        # first find its name
        motif_name = curated_motif_map[curated_motif_map["index"] == key]["gene_name"].iloc[0]
        f.write("MOTIF %s %s\n\n" % (key, motif_name))

        pwm = curated_pwms[key]
        n_bp = len(pwm)
        f.write("letter-probability matrix: alength= 4 w= %s\n" % n_bp)
        for pos in pwm:
            f.write("  %s\t%s\t%s\t%s\n" % (round(float(pos[0]), 5), round(float(pos[1]), 5), 
                                            round(float(pos[2]), 5), round(float(pos[3]), 5)))
        f.write("\n")
f.close()

## 5. check how many TFs in this list have orthologs according to Ensembl

In [74]:
orths_f = "../../04__ensembl_orthologs/ensembl_human_mouse_orthologs.txt.gz"
orths = pd.read_table(orths_f, sep="\t")
orths.head()

    Gene stable ID Gene name Mouse gene stable ID Mouse gene name
0  ENSG00000210049     MT-TF                  NaN             NaN
1  ENSG00000211459   MT-RNR1                  NaN             NaN
2  ENSG00000210077     MT-TV                  NaN             NaN
3  ENSG00000210082   MT-RNR2                  NaN             NaN
4  ENSG00000209082    MT-TL1                  NaN             NaN

In [75]:
curated_motif_map_orth = curated_motif_map.merge(orths, left_on="gene_id", right_on="Gene stable ID", how="left")
curated_motif_map_orth.head()

,index,gene_id,gene_name,Gene stable ID,Gene name,Mouse gene stable ID,Mouse gene name
0,HKR1,ENSG00000181666,HKR1,ENSG00000181666,HKR1,NaN,NaN
1,M00117_1,ENSG00000137203,TFAP2A,ENSG00000137203,TFAP2A,ENSMUSG00000021359,Tfap2a
2,M00118_1,ENSG00000137203,TFAP2A,ENSG00000137203,TFAP2A,ENSMUSG00000021359,Tfap2a
3,M00119_1,ENSG00000137203,TFAP2A,ENSG00000137203,TFAP2A,ENSMUSG00000021359,Tfap2a
4,M00120_1,ENSG00000137203,TFAP2A,ENSG00000137203,TFAP2A,ENSMUSG00000021359,Tfap2a

In [78]:
curated_motif_map_orth = curated_motif_map_orth[["index", "gene_id", "gene_name", 
                                                 "Mouse gene stable ID", "Mouse gene name"]]
curated_motif_map_orth.columns = ["motif_id", "human_gene_id", "human_gene_name", "mouse_gene_id", "mouse_gene_name"]
curated_motif_map_orth.sample(5)

,motif_id,human_gene_id,human_gene_name,mouse_gene_id,mouse_gene_name
2117,M05942_1,ENSG00000008441,NFIX,ENSMUSG00000001911,Nfix
3590,M08596_1,ENSG00000165891,E2F7,ENSMUSG00000020185,E2f7
2140,M05965_1,ENSG00000184221,OLIG1,ENSMUSG00000046160,Olig1
420,M01263_1,ENSG00000138136,LBX1,ENSMUSG00000025216,Lbx1
3232,M07241_1,ENSG00000180318,ALX1,ENSMUSG00000036602,Alx1

In [80]:
n_tot = len(curated_motif_map_orth["human_gene_name"].unique())
n_tot

927

In [82]:
n_orth = len(curated_motif_map_orth[~pd.isnull(curated_motif_map_orth["mouse_gene_id"])]["human_gene_name"].unique())
n_orth

751

In [83]:
# compare to lambert metadata file
cons_f = "00__metadata/TF_conservation.txt"
cons = pd.read_table(cons_f, sep=",")
cons.head()

,GENE,Human,Chimpanzee,Gorilla,Macaque,Marmoset,Mouse Lemur,Rat,Mouse,Rabbit,...,Fugu,Cod,Zebrafish,Spotted gar,Lamprey,C.savignyi,C.intestinalis,Fruitfly,C. elegans,S. cerevisiae
0,KLF15#ENSG00000163884,100,87.5,98.6,97.8,93.5,NaN,83.7,85.1,86.1,...,51.2,55.0,57.7,59.6,28.1,NaN,28.6,20.4,NaN,10.1
1,PRMT3#ENSG00000185238,100,99.6,89.8,90.2,96.8,51.4,89.3,90.0,93.0,...,58.2,57.4,59.1,62.9,NaN,NaN,45.0,37.9,NaN,27.7
2,KDM2A#ENSG00000173120,100,100.0,71.3,99.6,99.5,99.6,97.8,97.3,99.1,...,55.1,53.4,55.4,47.7,NaN,33.1,29.9,36.9,NaN,11.1
3,FOXJ2#ENSG00000065970,100,99.3,19.3,98.6,97.9,93.7,90.8,90.2,92.5,...,29.4,25.8,28.2,14.8,NaN,NaN,NaN,NaN,NaN,15.0
4,KLF12#ENSG00000118922,100,99.5,100.0,98.0,99.8,97.0,96.3,97.0,85.1,...,70.6,56.5,68.9,77.9,21.9,24.9,26.1,27.9,NaN,9.7

In [84]:
len(cons)

1635

In [85]:
cons["gene_id"] = cons["GENE"].str.split("#", expand=True)[1]
cons.head()

,GENE,Human,Chimpanzee,Gorilla,Macaque,Marmoset,Mouse Lemur,Rat,Mouse,Rabbit,...,Cod,Zebrafish,Spotted gar,Lamprey,C.savignyi,C.intestinalis,Fruitfly,C. elegans,S. cerevisiae,gene_id
0,KLF15#ENSG00000163884,100,87.5,98.6,97.8,93.5,NaN,83.7,85.1,86.1,...,55.0,57.7,59.6,28.1,NaN,28.6,20.4,NaN,10.1,ENSG00000163884
1,PRMT3#ENSG00000185238,100,99.6,89.8,90.2,96.8,51.4,89.3,90.0,93.0,...,57.4,59.1,62.9,NaN,NaN,45.0,37.9,NaN,27.7,ENSG00000185238
2,KDM2A#ENSG00000173120,100,100.0,71.3,99.6,99.5,99.6,97.8,97.3,99.1,...,53.4,55.4,47.7,NaN,33.1,29.9,36.9,NaN,11.1,ENSG00000173120
3,FOXJ2#ENSG00000065970,100,99.3,19.3,98.6,97.9,93.7,90.8,90.2,92.5,...,25.8,28.2,14.8,NaN,NaN,NaN,NaN,NaN,15.0,ENSG00000065970
4,KLF12#ENSG00000118922,100,99.5,100.0,98.0,99.8,97.0,96.3,97.0,85.1,...,56.5,68.9,77.9,21.9,24.9,26.1,27.9,NaN,9.7,ENSG00000118922

In [86]:
cons_sub = cons[cons["gene_id"].isin(curated_motif_map["gene_id"])]
len(cons_sub)

927

In [89]:
cons_sub_mouse_orth = cons_sub[cons_sub["Mouse"] > 0]
len(cons_sub_mouse_orth)

766

In [88]:
cons_sub_mouse_orth[cons_sub_mouse_orth["GENE"].str.contains("HKR1")]

,GENE,Human,Chimpanzee,Gorilla,Macaque,Marmoset,Mouse Lemur,Rat,Mouse,Rabbit,...,Cod,Zebrafish,Spotted gar,Lamprey,C.savignyi,C.intestinalis,Fruitfly,C. elegans,S. cerevisiae,gene_id
1564,HKR1#ENSG00000181666,100,93.5,97.6,94.1,0.0,83.5,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,ENSG00000181666

In [97]:
tmp = curated_motif_map_orth[pd.isnull(curated_motif_map_orth["mouse_gene_id"])]
len(tmp)

275

In [102]:
tmp[tmp["human_gene_name"] == "ZNF3"]

     motif_id    human_gene_id human_gene_name mouse_gene_id mouse_gene_name
5555     ZNF3  ENSG00000166526            ZNF3           NaN             NaN

In [103]:
len(cons_sub_mouse_orth[cons_sub_mouse_orth["gene_id"].isin(tmp["human_gene_id"])])

59

In [94]:
orths[orths["Gene stable ID"] == "ENSG00000184635"]

        Gene stable ID Gene name Mouse gene stable ID Mouse gene name
50183  ENSG00000184635     ZNF93                  NaN             NaN